version: '3.5'

services:

  front:
    image: kurkkumopo-frontend
    ports:
      - 3000:3000

  back:
    image: kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model

  training:
    image: kurkkumopo-training
    volumes:
      - imgs:/src/imgs
      - data:/src/data
      - model:/src/model

volumes:
  imgs:
  data:
  model:

