version: '3.5' 

services: 

    frontend: 
      image: frontend
      ports:
        - 5000:5000
      environment:
        - API_URL=http://localhost:8000

    backend: 
      image: backend
      ports:
        - 8000:8000
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis

    redis:
      image: redis
      ports: 
        - 6379:6379
